### ISSUE TITLE
Compare with other paper

### ISSUE THREAD

**Issue by tino123j** [Lcrypto/Belief-Propagation-decoder-of-Polar-Codes#2]
Hello! I have encountered some problems during the execution of the program.
I tried to simulate your code, and changed N=1024, m=10, iter4astep=10000, max_itter=40 .
32768_1_2.txt file has also been changed to 1024.txt .
However, BER/FER cannot be significantly reduced with the increase of SNR.
I don't know where the problem is, can you help me?

![SNR-BER/FER](https://www.researchgate.net/profile/Sha_Jin/publication/314083487/figure/fig3/AS:667868463112206@1536243658493/Performance-comparison-of-the-polar-codes-constructed-with-conventional-and-proposed.jpg)

**Comment by Lcrypto** [comment]
It reason of Trapping sets, cycles which you get  when broke Succesive constelation scheduller, you have gain in middle SNR area due soft information but after with increase of snr you get same or even worse than sc scheduller perfomance. One of the way to improve perfomance use several representation (normal graph automorphism, MacWilliams Authomorhism Group decoder, know as SC-List decoder) of same polar code. As result you shall get better than list sc polar code perfomance and on some level again same as sc list polar code perfomance. Another approach optimize frozen bit sequence of frozen bit for this type scheduller, you shall get same behaivior of curve but on lower level of Fer/BeR. With BR, USA.

**Comment by tino123j** [comment]
Sorry, I think my question is not clear enough.
The graph is the result of executing with your code.

![](https://i.imgur.com/Rxc1ptY.png)
![](https://i.imgur.com/18khaV9.png)
                                

![](https://i.imgur.com/rJiKLVa.png)



Compare with paper[Yingxian Zhang, "A Simplified Belief Propagation Decoder for Polar Codes"].
![](https://i.imgur.com/yPqDcDp.png)

Also in the case of SNR 3, the resulting BER differs a lot.
I am not sure if I have missing any steps.
I am directly compressing the code into the same folder and compiling the cpp file and executing it.


This is the result of the execution of my own program, in the case of a code length of 1024.(r=0.5)
Not sure why it is always worse than other papers

![](https://i.imgur.com/hupe3FK.png)

**Comment by Lcrypto** [comment]
Statistic not enought, better use at least 200 fer. Influence of differ frozzen bits position and need to simulated below 10^-5 or 6.

**Comment by tino123j** [comment]
Thanks a lot.
